// Presentation only. Stock, booking state, accounts and permissions belong to the existing API.
export function pwaHeader(city, escape, installing = false) {
  return `<header class="pwa-header"><a href="/app" class="brand" aria-label="Бери сегодня — предложения"><img class="brand-mark" src="/icons/icon-192.png" alt="" width="40" height="40" /><span class="brand-text"><strong>Бери сегодня</strong><small>${escape(city)}</small></span></a>${installing ? '<a class="pwa-install-link" href="/">На сайт</a>' : '<a class="pwa-install-link" href="/install">Установить</a>'}</header>`;
}

export function pwaNavigation(pathname, icon) {
  const selected = pathname.startsWith("/booking/") ? "/app/bookings" : pathname === "/partner/login" ? "/app/partners" : pathname;
  const tabs = [["/app", "Предложения", "bag"], ["/app/bookings", "Мои брони", "ticket"], ["/app/profile", "Профиль", "user"], ["/app/partners", "Партнёрам", "shop"]];
  return `<nav class="pwa-bottom-nav" aria-label="Разделы приложения">${tabs.map(([href, label, name]) => `<a href="${href}"${selected === href ? ' aria-current="page"' : ""}>${icon(name)}<span>${label}</span></a>`).join("")}</nav>`;
}

export function pwaPage(pathname, { grid, drawer, profile, icon }) {
  if (pathname === "/app") return `<section class="pwa-screen pwa-catalog"><div class="pwa-screen-heading"><div><p class="kicker">Забрать сегодня</p><h1>Предложения</h1></div><button class="pwa-refresh" type="button" data-refresh-offers aria-label="Обновить предложения">${icon("refresh")}</button></div><p class="pwa-lead">Забронируйте здесь, оплатите в магазине.</p>${grid()}${drawer()}</section>`;
  if (pathname === "/app/profile") return `${profile()}<button class="button button-outline pwa-tour-trigger" type="button" data-pwa-tour-start>Как забронировать</button>`;
  if (pathname === "/app/bookings") return `<section class="pwa-screen" data-pwa-bookings><h1>Мои брони</h1><p role="status" aria-live="polite" data-pwa-bookings-status>Загружаем брони…</p><div data-pwa-account-bookings></div><section data-pwa-guest-section hidden><h2>Без кабинета, на этом устройстве</h2><div data-pwa-guest-bookings></div></section><div class="pwa-empty" data-pwa-bookings-empty hidden>${icon("ticket")}<h2>Здесь будет ваш код</h2><p>Выберите предложение и забронируйте. Регистрация не нужна.</p><a class="button button-primary" href="/app">Выбрать предложение</a></div><aside class="pwa-note" data-pwa-profile-note hidden><h2>Хотите видеть брони на других устройствах?</h2><p>Войдите по почте. Брони, оформленные после входа, появятся и на сайте, и в Android.</p><a href="/app/profile">Войти по почте</a></aside><button class="button button-outline" type="button" data-pwa-bookings-refresh>Обновить</button></section>`;
  if (pathname === "/app/partners") return `<section class="pwa-screen"><p class="kicker">Для заведений</p><h1>Партнёрам</h1><article class="pwa-entry-card">${icon("shop")}<h2>Уже работаете с нами?</h2><p>Войдите с логином и паролем, которые получили при подключении.</p><a class="button button-primary" href="/partner/login?app=1">Вход для партнёра</a></article><article class="pwa-entry-card"><h2>Хотите подключить заведение?</h2><p>Расскажите о своей точке. Мы свяжемся с вами и поможем разместить первое предложение.</p><a class="button button-outline" href="/partners?app=1#partner-application">Оставить заявку</a></article><a class="pwa-admin-link" href="/admin?app=1">Вход для администратора</a><p class="pwa-small">Для покупателя вход не обязателен. Предложения и бронь — в первом разделе.</p></section>`;
  return "";
}

export function installPage(icon) {
  return `<section class="install-page"><img src="/icons/icon-192.png" alt="" width="88" height="88" /><h1>Бери сегодня — в телефоне</h1><p>Выберите свой телефон.</p><div class="install-options"><article><h2>Android</h2><p>Скачайте приложение и откройте скачанный файл.</p><a class="button button-primary" href="/downloads/beri-segodnya-android-0.3.0-native-pilot.apk" download>${icon("smartphone")} Скачать для Android</a><p class="pwa-small">Если телефон спросит разрешение на установку из браузера, разрешите только эту установку. После установки отключите разрешение.</p></article><article><h2>iPhone</h2><p>Добавьте приложение на экран «Домой». App Store не нужен.</p><a class="button button-primary" href="/iphone">Установить на iPhone</a></article></div><div class="install-qr"><img src="/icons/install-qr.svg" alt="QR-код страницы установки «Бери сегодня»" width="220" height="220" /><p>Откройте эту страницу на телефоне с помощью камеры.</p></div><a href="/app">Открыть приложение без установки</a></section>`;
}

export function iphonePage() {
  return `<section class="install-page iphone-install"><img src="/icons/apple-touch-icon.png" alt="" width="88" height="88" /><h1>Бери сегодня на iPhone</h1><p>Приложение появится на экране «Домой» и будет открываться отдельно от сайта.</p><ol class="iphone-steps"><li><strong>Откройте в Safari</strong><span>Если вы перешли из Telegram или другого приложения, откройте эту ссылку в Safari.</span></li><li><strong>Перейдите в приложение</strong><span>Нажмите кнопку ниже. Откроются предложения и нижнее меню.</span></li><li><strong>Добавьте на экран «Домой»</strong><span>В Safari нажмите «Поделиться» → «На экран “Домой”». Если есть пункт «Открыть как веб-приложение», включите его. Затем нажмите «Добавить».</span></li><li><strong>Открывайте с иконки</strong><span>Выйдите из Safari и нажмите значок «Бери сегодня» на экране телефона.</span></li></ol><a class="button button-primary" href="/app?install=iphone">Открыть приложение</a><p class="pwa-small">Регистрация не нужна для первой брони. В профиль можно войти позже, чтобы сохранять контакты и видеть историю на разных устройствах.</p><a href="/install">Выбрать другой телефон</a></section>`;
}
